### ISSUE TITLE
New song not saving to DB

### ISSUE THREAD

**Issue by alexi-o** [den-materials/tunely#1]
I've console.logged everything and can't see where I've gone wrong and I'm not receiving any errors. The song will add to the album but disappears on refresh and isn't saving to the database.

I've discussed the issue with Alex.

http://stackoverflow.com/questions/17793666/mongodb-not-saving-data
http://stackoverflow.com/questions/40756335/my-local-mongodb-instance-is-not-saving-data-via-express-and-mongoose

**Comment by alexi-o** [comment]
Problem solved. My song sheeemah was written incorrectly 👍

**Comment by ZebGirouard** [comment]
#closedByAlexi
